apiVersion: v1
kind: ConfigMap
metadata:
  name: yandex-cloud-metrics
data:
  yandex-cloud-metrics.yaml: |
    - job_name: 'yandex-cloud-monitoring'
      metrics_path: '/monitoring/v2/prometheusMetrics'
      params:
        folderId: ['b1gs0cg1voiht42pp513']
      static_configs:
        - targets: ['monitoring.api.cloud.yandex.net']
      scheme: https
      authorization:
        credentials_file: /etc/prometheus/secrets/yandex-key/key.json
      tls_config:
        insecure_skip_verify: true