apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: backend
          image: nesterrovv/cvet-ochey:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_DRIVER
              value: "jdbc:postgresql"
            - name: DATABASE_HOST
              value: "postgres"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_LOGIN
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: login
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: database
          resources:
            requests:
              cpu: "100m"