server:
  port: 8080

spring:
  application:
    name: cvet-ochey
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false
  datasource:
    url: ${DATABASE_DRIVER}://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_LOGIN}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: backend
      service: cvetochey-backend
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
    web:
      server:
        request:
          autotime:
            enabled: true
            percentiles: 0.5, 0.95, 0.99
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours
  refresh-token:
    expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days