name: CI

on:
  push:
    branches:
      - master
      - devg
  pull_request:

jobs:
  build-backend:
    name: Backend build, checkstyle and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and Test with Maven
        working-directory: ./backend
        run: mvn clean install

      - name: Run Checkstyle
        working-directory: ./backend
        run: mvn checkstyle:check

  build-frontend:
    name: Frontend build, checkstyle and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build NextJS
        working-directory: ./frontend
        run: npm run build

      - name: Run tests
        working-directory: ./frontend
        run: npm test
