name: CI

on:
  push:
    branches:
      - master
      - devg
  pull_request:

jobs:
  build-backend:
    name: Backend build, checkstyle and tests
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15.2
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: cvetochey
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test -d cvetochey"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Ping db host in container
        run: ping -c 4 db

      - name: Build and Test with Maven
        working-directory: ./backend
        env:
          DATABASE_DRIVER: jdbc:postgresql
          DATABASE_HOST: db
          DATABASE_PORT: 5432
          DATABASE_LOGIN: test
          DATABASE_PASSWORD: test
          DATABASE_NAME: cvetochey
        run: mvn clean install

      - name: Run Checkstyle
        working-directory: ./backend
        run: mvn checkstyle:check

  build-frontend:
    name: Frontend build, checkstyle and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'

      - name: Install dependencies
        working-directory: ./frontend
        run: yarn

      - name: Run linters
        working-directory: ./frontend
        run: yarn run lint

#      - name: Run tests
#        working-directory: ./frontend
#        run: npm test

      - name: Build NextJS
        working-directory: ./frontend
        run: yarn run build
